jwt:
  expiration-time: ${JWT_EXPIRATION_TIME}
  refresh-token-expiration-time: ${REFRESH_TOKEN_EXPIRATION_TIME}
# Logging
logging:
  level:
    com.subride.member.infra.in: INFO
    com.subride.member.infra.out: INFO